### ISSUE TITLE
How to remove the anotation and the extra functions ,remaining only clean struct?

### ISSUE THREAD

**Issue by fwhezfwhez** [achiku/dgw#8]
In the guide case I get:
```go
// Class represents public.class
type Class struct {
	ID   int             // id
	Age  sql.NullInt64   // age
	Name sql.NullString  // name
	Sal  sql.NullFloat64 // sal
}
// Create inserts the Class to the database.
func (r *Class) Create(db Queryer) error {
	err := db.QueryRow(
		`INSERT INTO class (age, name, sal) VALUES ($1, $2, $3) RETURNING id`,
		&r.Age, &r.Name, &r.Sal).Scan(&r.ID)
	if err != nil {
		return errors.Wrap(err, "failed to insert class")
	}
	return nil
}

// GetClassByPk select the Class from the database.
func GetClassByPk(db Queryer, pk0 int) (*Class, error) {
	var r Class
	err := db.QueryRow(
		`SELECT id, age, name, sal FROM class WHERE id = $1`,
		pk0).Scan(&r.ID, &r.Age, &r.Name, &r.Sal)
	if err != nil {
		return nil, errors.Wrap(err, "failed to select class")
	}
	return &r, nil
}
```

**Comment by fwhezfwhez** [comment]
By the way , db_types 'character varying'  didn't work.
I config like
```toml
[string]
db_types = ["character", "character varying", "text", "money", "uuid", "varchar"]
notnull_go_type = "string"
nullable_go_type = "string"
```
But got
```
...
	F103            interface{}
...
```
The field 'F103' in postgres is charactor varying
